project:
  type: website
  output-dir: docs

website:
  title: "Jason Laird"
  page-footer:
    left:
      - text: "Â© 2026 Jason Laird"
    right:
      - icon: github
        href: https://github.com/BioNomad
      - icon: linkedin
        href: https://www.linkedin.com/in/jason-laird-78b9b116b/
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: index.qmd#projects
      - text: "CV"
        href: cv2.qmd
      - text: "Posts"
        href: post_idx.qmd
      - text: "Contact"
        href: index.qmd#contact
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



